# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea815cad61a7c69b09f93b18abd93605455adf72589ca0da61b28e27023963ec66ee33d54582f9047b40dd3ac09a5f4b199fc14032bd96b1a6fcde7c1cbeecd

test:
  secret_key_base: 3cd6eef857f7d148f22f22aa9d54f4cf2bdd73efe773632bcd2649cb6647a395dbe45d7c73fcfe4c9a39586ab9d4ef630958a05a24a1abc576fcd5057a6ad61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
